### ISSUE TITLE
classifier_mapper takes incorrect 'gamma' value for rbf SVMs

### ISSUE THREAD

**Issue by FDillk** [abstract-machine-learning/data-collection#1]
Hey, 

not sure if you're still maintaining this repo, but I think i have discovered a bug.
While converting model to use your SAVer tool, I noticed problems when converting sklearn SVMs with an rbf kernel.
The problem stems from line 35 in the classifier_mapper.py:
**csv_writer.writerow(['rbf', classifier.gamma])**

When no float value is specified during training of the model, the value of classifier.gamma is 'scale' or 'auto'.
Your format however is expecting the actual gamma float value at this point, so per sklearn documentation, the value has to be calculated with:
**1 / (n_features * X.var())**, for gamma = 'scale'
or
**1 / n_features**, for gamma = 'auto'

This calculation could be integrated at that point in the code, but I'm unsure if this repository is still maintained.

Best wishes

**Comment by marco-zanella** [comment]
Thank you for highlighting this, that would be definitively nice to have, I will update the code in the next few days.
Since classifier_mapper is not supposed to have access to n_feature or X but expects to deal with classifiers trained by svm.py, I will probably inject the computation of gamma in the latter.

**Comment by marco-zanella** [comment]
Implemented in https://github.com/abstract-machine-learning/data-collection/commit/39f9ba9143bce3163f2a3d436637f4e9aea9f1d8
Thank you!
